apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-2022bcd0028
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-2022bcd0028
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi